### ISSUE TITLE
send exception message instead of "Server error"

### ISSUE THREAD

**Issue by BlackZork** [bcb/jsonrpcserver#71] opened 2018-09-28 15:15 UTC
When RPC methods raises an exception there is always the same reply returned:

`INFO jsonrpcclient.client.response: {"jsonrpc": "2.0", "error": {"code": -32000, "message": "Server error"}, "id": 2}`

It would be great if 'message' could contain str(exception) that was thrown by called method.

**Comment by bcb** [comment] 2018-09-28 20:39
You can pass `debug=True` to `dispatch` to include more info in the response message.

**Comment by BlackZork** [comment] 2018-09-30 12:17
Is it ok to use debug=True in production code?

**Comment by bcb** [comment] 2018-09-30 21:29
Generally you wouldn't want the client seeing your exception messages, for security reasons, but it depends on your situation.

**Comment by BlackZork** [comment] 2018-10-01 07:08
I could decorate my rpc methods, catch exceptions and send my own messages like { result: False, data: <exception info> }, but this is creating a protocol inside protocol. 

You are right that passing str(exception) as message is not a good idea, but maybe jsonrpcserver should have a way to provide error message from client code when exception is raised. 
For me it would be great if I could register my own exception handler that will return a string that will be later sent in json reply.

**Comment by seidlmic** [comment] 2019-01-29 20:07
As I am looking in code, is it true that before ver. 4.0 I can not easily implement my own exceptions with application specific return codes.  In other words I have to use protocol inside protocol mentioned above? Am I right? Is there plan to update 3.x version.

**Comment by bcb** [comment] 2019-01-30 07:42
Yes we can update the 3.x version if needed.

Can you show me what the response message would look like?

**Comment by seidlmic** [comment] 2019-01-30 11:36
I would like to implement application defined errors with specific code, message and data (https://www.jsonrpc.org/specification#response_object). So something like
`{"jsonrpc": "2.0", "error": {"code": -32800, "message": "Invalid input geometry", "data": {"index": 33, "coordinates": [1135.124, -25689]}}, "id": "1"}`
I would like to raise application defined exception in rpc method that I would handle in the way shown above. I am working with geo data that are not always perfect.

**Comment by okke-formsma** [comment] 2019-02-12 10:01
I have the same issue as @seidlmic.

One approach would be to raise a ExceptionResponse from inside the method.  This way, all 'specially handled' exceptions will get the proper response, and 'normal' exceptions get the generic jsonrpc exception handling.

To make this happen, we only have to adjust the handle_exceptions call to catch ExceptionResponses and rethrow them.

**Comment by ixje** [comment] 2019-03-14 12:10
Same! Was about to open an issue to request this feature. It's to only reason I had to pass on from using this (for now). The rest looked really convenient to use.

**Comment by steinymity** [comment] 2019-10-25 15:54
Is there already work in progress on this matter? If not, I'd like to volunteer as I am also really interested in this feature.

**Comment by bcb** [comment] 2019-10-25 18:47
For the example given above, “Invalid input geometry“, you should raise an AssertionError for input validation.

There’s a catch-all which responds to any “other” exception with just “server error” and no other information. To me this is correct, the client shouldn’t see exception messages unless debug mode is enabled.

I think the issue is it’s responding with “server error” and then swallowing the exception, it should be logging it so the developer can see the problem.

**Comment by bcb** [comment] 2019-10-25 18:49
Happy to receive PRs @steinymity

**Comment by steinymity** [comment] 2019-10-25 20:14
@bcb I agree, there should be a catchall that just logs the exception and responds with a generic "Server exception" without too much detail.

Apart from that I can imagine that API functions can raise an "ApiException" with a message, code and optionally more details that can be used for custom, application-specific errors. In that way, library users can actually use the error signaling mechanisms of the json-rpc protocol.

I'll hack some code and open a PR :)

**Comment by bcb** [comment] 2019-10-26 00:36
Sounds like this would replace the AssertionError mechanism we already have, but it would allow using specifying the `code` part of the response, which

**Comment by bcb** [comment] 2019-10-26 01:15
Rephrasing, to be clear

For input validation we have this
https://jsonrpcserver.readthedocs.io/en/latest/api.html#validation

For errors on the server side, say a file doesn’t exist, you can raise any exception like FileNotFoundError which responds with server error, and no more information. (it should be logged on the server end)

I’m looking for an example which these two scenarios don’t cover.

**Comment by steinymity** [comment] 2019-10-26 07:30
Let's say, the client tries to read a file. This can fail for various reasons (file does not exist, client has no permission, …). The server can currently only raise an exception which results in a generic "Server Error". The client can't tell why this happened, even if the server wanted the client to know this.Or, put very simply, the jsonrpc standard allows custom error codes, messages, and data, and there is currently no way to set all these three freely.

This functionality is not covered by the `debug` flag since there might also be simple programming errors and unanticipated server-side errors. In this case, a generic server exception is reasonable in order not to leak any server internals.

**Comment by bcb** [comment] 2019-10-26 12:32
Ok sounds good, let’s do it. Look forward to your PR.

**Comment by bcb** [comment] 2019-11-15 04:06
Fixed in #94

**Closed by bcb** 2019-11-15 04:06 UTC
